### PR TITLE
cdata decodoing

### PR DESCRIPTION
**Pull request by Amedeo91**
I start to propose some changes to the issue I opened. I did not completely test them, so provide any feedback! :)

### CODE REVIEW

**Comment by Arzaroth** [comment]
As said in #1, if this passes CI (given you provide tests for the new functionality), I'll be happy to merge it.

**Comment by Amedeo91** [comment]
yes, I currently have some issue in running the test! :)

**Comment by Amedeo91** [comment]
@Arzaroth I finished the development, adding a new test in the unit test.

Regards,
Amedeo

**Comment by Amedeo91** [comment]
Hi @Arzaroth,

Did you have the chance to check the PR? 

I actually need this new feature quite soon! :)

Thank you and kind regards,
Amedeo

**Pull request closed without merging**
